apiVersion: V1
kind: deployment
metadata: javawebappdeployment
spec:
  replicas: 2
  selectors:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapppod
      spec:
        containers:
        - name: javawebappcontainer
          image: smdrafiq/java-web-app
          ports:
          - containerport: 8080

                   
